#!/usr/bin/env python3
"""Turn GNU Unifont's .hex dump into the two font artefacts this project uses.

  assets/font_ascii.inc   ASCII 0x20-0x7E as an 8x16 C array, compiled into the
                          binary so the app can always draw an activation code
                          and an error message without an external file.

  build/font.bin          C1FONT1: ASCII plus a CJK subset, deployed next to the
                          executable and memory mapped at runtime. Kept out of
                          the binary because the full CJK range is about 1 MB.

C1FONT1 layout, little endian throughout:

  offset 0   magic "C1FONT1\\0"        8 bytes
  offset 8   glyph height              u16
  offset 10  reserved                  u16
  offset 12  glyph count               u32
  offset 16  index[count]              { u32 codepoint; u8 width; u8 pad[3]; }
  then       rows, 16-bit per row, `height` rows per glyph, in index order

The index is sorted by codepoint so the renderer can binary search it.
"""

import argparse
import os
import struct
import sys

# Ranges worth carrying on a 296x152 screen. CJK Unified Ideographs is the bulk;
# everything else is punctuation, kana and full-width forms that Chinese text
# mixes in.
DEFAULT_RANGES = [
    (0x0020, 0x007E),  # ASCII
    (0x00A0, 0x00FF),  # Latin-1 supplement
    (0x2000, 0x206F),  # general punctuation
    (0x2190, 0x21FF),  # arrows
    (0x2460, 0x24FF),  # enclosed alphanumerics
    (0x25A0, 0x25FF),  # geometric shapes
    (0x2600, 0x26FF),  # misc symbols
    (0x3000, 0x303F),  # CJK symbols and punctuation
    (0x3040, 0x30FF),  # kana
    (0x4E00, 0x9FFF),  # CJK unified ideographs
    (0xFF00, 0xFFEF),  # halfwidth and fullwidth forms
]


def parse_hex(path):
    """Yields (codepoint, width, [row, ...]) with rows as 16-bit ints."""
    glyphs = {}
    with open(path, "r", encoding="ascii") as handle:
        for line in handle:
            line = line.strip()
            if not line or ":" not in line:
                continue
            code_text, bitmap = line.split(":", 1)
            codepoint = int(code_text, 16)
            # 32 hex digits is 8 wide, 64 is 16 wide. Unifont uses 16 rows.
            if len(bitmap) == 32:
                width = 8
                rows = [int(bitmap[i:i + 2], 16) << 8 for i in range(0, 32, 2)]
            elif len(bitmap) == 64:
                width = 16
                rows = [int(bitmap[i:i + 4], 16) for i in range(0, 64, 4)]
            else:
                continue
            glyphs[codepoint] = (width, rows)
    return glyphs


def in_ranges(codepoint, ranges):
    return any(low <= codepoint <= high for low, high in ranges)


def write_binary(path, glyphs, height):
    ordered = sorted(glyphs.items())
    with open(path, "wb") as out:
        out.write(b"C1FONT1\0")
        out.write(struct.pack("<HHI", height, 0, len(ordered)))
        for codepoint, (width, _rows) in ordered:
            out.write(struct.pack("<IBBBB", codepoint, width, 0, 0, 0))
        for _codepoint, (_width, rows) in ordered:
            for row in rows:
                out.write(struct.pack("<H", row))
    return len(ordered)


def write_ascii_include(path, glyphs):
    lines = [
        "// Generated by tools/build_font.py from GNU Unifont. Do not edit.",
        "// ASCII 0x20-0x7E, 8 pixels wide, 16 rows, one byte per row.",
        "static const unsigned char kAsciiFont8x16[95][16] = {",
    ]
    for codepoint in range(0x20, 0x7F):
        entry = glyphs.get(codepoint)
        if entry is None:
            rows = [0] * 16
        else:
            # The compiled-in fallback is 8 wide; take the high byte.
            rows = [(row >> 8) & 0xFF for row in entry[1]]
        body = ", ".join("0x%02x" % row for row in rows)
        lines.append("    {%s},  // U+%04X" % (body, codepoint))
    lines.append("};")
    lines.append("")
    with open(path, "w", encoding="ascii") as out:
        out.write("\n".join(lines))


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--hex", default=os.path.join(here, "third_party", "unifont.hex"))
    parser.add_argument("--ascii-out", default=os.path.join(here, "assets", "font_ascii.inc"))
    parser.add_argument("--bin-out", default=os.path.join(here, "build", "font.bin"))
    parser.add_argument("--full", action="store_true",
                        help="include every glyph in the hex file, not just the default ranges")
    args = parser.parse_args()

    if not os.path.exists(args.hex):
        sys.exit("unifont hex not found at %s; run tools/fetch-deps.sh" % args.hex)

    all_glyphs = parse_hex(args.hex)
    if not all_glyphs:
        sys.exit("no glyphs parsed from %s" % args.hex)

    os.makedirs(os.path.dirname(args.ascii_out), exist_ok=True)
    write_ascii_include(args.ascii_out, all_glyphs)
    print("wrote %s" % args.ascii_out)

    if args.full:
        selected = all_glyphs
    else:
        selected = {cp: g for cp, g in all_glyphs.items() if in_ranges(cp, DEFAULT_RANGES)}

    os.makedirs(os.path.dirname(args.bin_out), exist_ok=True)
    count = write_binary(args.bin_out, selected, 16)
    size = os.path.getsize(args.bin_out)
    print("wrote %s: %d glyphs, %.1f KiB" % (args.bin_out, count, size / 1024.0))


if __name__ == "__main__":
    main()
